### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by baobz** [huangang/wepy-one#3]
我从git上拉的项目将本地的src文件替换掉后运行报错
Uncaught ReferenceError: regeneratorRuntime is not defined
pages/index/index.js 出现脚本错误或者未正确调用 Page()

**Comment by huangang** [comment]
微信开发者工具-->设置-->项目设置-->关闭ES6转ES5

**Comment by huangang** [comment]
@baobz 微信开发者工具-->设置-->项目设置-->关闭ES6转ES5
